# Generated by Django 4.0.5 on 2022-06-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comics',
            new_name='comic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite',
        ),
    ]
